spring:
  application:
    name: peauty-customer
  profiles:
    active: customer-local
    include:
      - persistence
      - aws
      - auth
  jackson:
    default-property-inclusion: non_null

iamport:
  api-key: ${IAMPORT_API_KEY}
  api-secret-key: ${IAMPORT_API_SECRET_KEY}


---
spring:
  config:
    activate:
      on-profile:
        - customer-local

server:
  port: 8080
  shutdown: graceful
  domain: http://localhost:8080

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha      # 태그 정렬
    operations-sorter: alpha  # API 정렬
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring:
  config:
    activate:
      on-profile:
        - customer-dev

server:
  port: 8080
  shutdown: graceful
  domain: https://customer-dev.peauty.click

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha      # 태그 정렬
    operations-sorter: alpha  # API 정렬
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    root: warn

---
spring:
  config:
    activate:
      on-profile: customer-prod

server:
  port: 8080
  shutdown: graceful
  domain: https://customer.peauty.click

logging:
  level:
    root: warn