spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/aws.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      resolve-lazily: true