oauth:
  kakao-client-id: ${KAKAO_CLIENT_ID}
  apple-client-id: ${APPLE_CLIENT_ID}
  google-client-id: ${GOOGLE_CLIENT_ID}
  google-client-secret: ${GOOGLE_CLIENT_SECRET}
  kakao-public-key-info: https://kauth.kakao.com/.well-known/jwks.json
  apple-public-key-url: https://appleid.apple.com/auth/keys

---
spring:
  config:
    activate:
      on-profile: customer-local
oauth:
  kakao-redirect-url: http://localhost:8080/v1/auth/kakao-sign-in
  apple-redirect-url: http://localhost:8080/v1/auth/apple-sign-in
  google-redirect-url: http://localhost:8080/v1/auth/google-sign-in
  frontend-redirect-url: /v1/auth/test

---
spring:
  config:
    activate:
      on-profile: customer-dev
oauth:
  kakao-redirect-url: https://customer-dev.peauty.click/v1/auth/kakao-sign-in
  apple-redirect-url: https://customer-dev.peauty.click/v1/auth/apple-sign-in
  google-redirect-url: https://customer-dev.peauty.click/v1/auth/google-sign-in
  frontend-redirect-url: http://localhost:5174 # TODO https://peauty.click 로 바꾸기

---
spring:
  config:
    activate:
      on-profile: customer-prod
oauth:
  kakao-redirect-url: https://customer.peauty.click/v1/auth/kakao-sign-in
  apple-redirect-url: https://customer.peauty.click/v1/auth/apple-sign-in
  google-redirect-url: https://customer.peauty.click/v1/auth/google-sign-in
  frontend-redirect-url: https://peauty.click

---
spring:
  config:
    activate:
      on-profile: designer-local
oauth:
  kakao-redirect-url: http://localhost:8081/v1/auth/kakao-sign-in
  apple-redirect-url: http://localhost:8081/v1/auth/apple-sign-in
  google-redirect-url: http://localhost:8081/v1/auth/google-sign-in
  frontend-redirect-url: http://localhost:8081/v1/auth/test

---
spring:
  config:
    activate:
      on-profile: designer-dev
oauth:
  kakao-redirect-url: https://designer-dev.peauty.click/v1/auth/kakao-sign-in
  apple-redirect-url: https://designer-dev.peauty.click/v1/auth/apple-sign-in
  google-redirect-url: https://designer-dev.peauty.click/v1/auth/google-sign-in
  frontend-redirect-url: http://localhost:5174 # TODO https://peauty.click 로 바꾸기

---
spring:
  config:
    activate:
      on-profile: designer-prod
oauth:
  kakao-redirect-url: https://designer.peauty.click/v1/auth/kakao-sign-in
  apple-redirect-url: https://designer.peauty.click/v1/auth/apple-sign-in
  google-redirect-url: https://designer.peauty.click/v1/auth/google-sign-in
  frontend-redirect-url: https://peauty.click