spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test  # 인메모리 H2 데이터베이스
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true  # H2 콘솔 활성화 (http://localhost:8080/h2-console)
  hibernate:
    ddl-auto: update  # 애플리케이션이 시작될 때 DB 스키마를 자동으로 업데이트
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2에 맞는 Hibernate dialect 설정

---
spring:
  config:
    activate:
      on-profile: beta

---
spring:
  config:
    activate:
      on-profile: real
