server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: peauty-designer
  profiles:
    active: local
    include:
      - persistence
      - aws
      - auth
  jackson:
    default-property-inclusion: non_null