workflow_dispatch:
  inputs:
    profile:
      description: '프로파일을 선택하세요 (real 또는 beta)'
      required: true
      default: 'beta'
      type: choice
      options:
        - real
        - beta
    package:
      description: '배포할 패키지를 선택하세요'
      required: true
      default: 'customer'
      type: choice
      options:
        - customer
        - designer